### ISSUE TITLE
Breaks at Mx 10.24

### ISSUE THREAD

**Issue by spaansl** [IncentroBA/backhandler#2]
Doesn't work in Mx 10.24. Would be greatly appreciated if it could be fixed since this widget a great addition to the platform.

**Comment by me-idris** [comment]
Also not working on 10.24 for me, this is the error I received when simply closing the page (using a nanoflow and a button).


`TypeError: v.BackHandler.removeEventListener is not a function (it is undefined)

This error is located at:
    in f
    in f
    in e
    in pluginWidget(f)
    in Unknown
    in e
    in pluginWidget()
    in Unknown
    in e
    in pluginWidget()
    in RCTView
    in Unknown
    in v
    in v
    in e
    in pluginWidget(v)
    in Unknown
    in e
    in pluginWidget()
    in RCTView
    in Unknown
    in v
    in v
    in e
    in pluginWidget(v)
    in RCTView
    in Unknown
    in RNCSafeAreaView
    in Unknown
    in RCTView
    in Unknown
    in Unknown
    in e
    in pluginWidget()
    in Unknown
    in RCTView
    in Unknown
    in Pt
    in RNCSafeAreaProvider
    in Unknown
    in RCTView
    in Unknown
    in Unknown
    in Et
    in Unknown
    in Unknown
    in Unknown
    in RCTView
    in Unknown
    in RCTView
    in Unknown
    in RCTView
    in Unknown
    in Unknown
    in RCTView
    in Unknown
    in Unknown
    in PanGestureHandler
    in Unknown
    in RCTView
    in Unknown
    in Unknown
    in RCTView
    in Unknown
    in r
    in a
    in RNSScreen
    in Unknown
    in u
    in Suspense
    in Unknown
    in Unknown
    in Unknown
    in Unknown
    in Unknown
    in RNSScreenContainer
    in Unknown
    in Unknown
    in RCTView
    in Unknown
    in b
    in RCTView
    in Unknown
    in f
    in RNGestureHandlerRootView
    in Unknown
    in l
    in Unknown
    in t
    in Unknown
    in a
    in Unknown
    in Unknown
    in Unknown
    in Unknown
    in RCTView
    in Unknown
    in RCTView
    in Unknown
    in Unknown
    in Unknown
    in Unknown
    in RNSScreen
    in Unknown
    in u
    in Suspense
    in Unknown
    in Unknown
    in Unknown
    in Unknown
    in Unknown
    in RNSScreenContainer
    in Unknown
    in Unknown
    in RCTView
    in Unknown
    in RCTView
    in Unknown
    in AnimatedComponent(TopLevelView)
    in Unknown
    in RCTView
    in Unknown
    in AnimatedComponent(TopLevelView)
    in Unknown
    in t
    in AnimatedComponent(t)
    in Unknown
    in Unknown
    in RNGestureHandlerRootView
    in Unknown
    in Unknown
    in p
    in RNCSafeAreaProvider
    in Unknown
    in f
    in Unknown
    in Unknown
    in t
    in Unknown
    in o
    in Unknown
    in Unknown
    in Unknown
    in c
    in RCTView
    in Unknown
    in Unknown
    in Ct
    in RNGestureHandlerRootView
    in Unknown
    in Ut
    in n
    in RCTView
    in Unknown
    in Unknown, js engine: hermes`

Followed by this error 
`v.BackHandler.removeEventListener is not a function (it is undefined)

Current page: Module.Page

Stack:
TypeError: v.BackHandler.removeEventListener is not a function (it is undefined)`

**Comment by me-idris** [comment]
Also not working on 10.24 for me, this is the error I received when simply closing the page (using a nanoflow and a button).

```TypeError: v.BackHandler.removeEventListener is not a function (it is undefined)

This error is located at:
in f
in f
in e
in pluginWidget(f)
in Unknown
in e
in pluginWidget()
in Unknown
in e
in pluginWidget()
in RCTView
...
...
...
```

Followed by this error
```v.BackHandler.removeEventListener is not a function (it is undefined)

Current page: Module.Page

Stack:
TypeError: v.BackHandler.removeEventListener is not a function (it is undefined)
...
...
...
```

**Comment by SrirangK** [comment]
Hey has anyone got a solution / replacement for the issue in 10.24

**Comment by me-idris** [comment]
> Hey has anyone got a solution / replacement for the issue in 10.24

I believe the fork from Andries-Smit [here ](https://github.com/Andries-Smit/backhandler) fixes this issue.

**Comment by SrirangK** [comment]
> > Hey has anyone got a solution / replacement for the issue in 10.24
> 
> I believe the fork from Andries-Smit [here ](https://github.com/Andries-Smit/backhandler) fixes this issue.

Thanks
